name: Automated Release

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: Commit SHA, tag or branch name (usually main branch)
        required: true
        default: "main"
        type: string
      version:
        description: Release version (semver without v prefix, e.g. 0.1.0)
        required: true
        type: string

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at git ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.gitRef }}
          token: ${{ secrets.KUADRANT_DEV_PAT }}

      - name: Prepare release branch
        id: prepare-branch
        uses: ./.github/actions/prepare-release-branch
        with:
          version: ${{ github.event.inputs.version }}
          push-branch: 'true'
          expiry: 'never'

      - name: Create Pull Request
        if: ${{ !env.ACT }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.KUADRANT_DEV_PAT }}
          commit-message: "Release v${{ github.event.inputs.version }}"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: true
          base: ${{ steps.prepare-branch.outputs.branch-name }}
          branch: release-v${{ github.event.inputs.version }}
          delete-branch: true
          title: "[Release] Developer Portal Controller v${{ github.event.inputs.version }}"
          body: |
            Prepare release v${{ github.event.inputs.version }}

            ## Changes
            - Updated VERSION in Makefile to ${{ github.event.inputs.version }}
            - Updated QUAY_IMAGE_EXPIRY in Makefile to never

            ## Post-merge
            After this PR is merged, a workflow will automatically:
            - Create git tag v${{ github.event.inputs.version }}
            - Create GitHub release
            - Build and push image to quay.io

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          team-reviewers: |
            Kuadrant/developers
          draft: false
