name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release-v[0-9]+.[0-9]+'
  workflow_dispatch: {}

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.KUADRANT_DEV_PAT }}
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Create release
        uses: ./.github/actions/create-release
        with:
          github-token: ${{ secrets.KUADRANT_DEV_PAT }}
